Update utils.ts
mcu-debug/peripheral-viewer pull request #27
Opened 2024-01-04 07:02 UTC by EGOKM

dimIndex now allows starting from zero

2024-01-04 07:50 UTC, kossnikita requested changes

2024-01-04 07:50 UTC, kossnikita commented on src/utils.ts
> +/*        if (!start || !end) {
Actually this is necessary `undefined` check
You can replace this with

```ts
if (start === undefined || end === undefined) {
    return [];
}
```

2024-01-04 07:50 UTC, kossnikita commented on src/utils.ts
> +	    if ( start < 0 || end < 0 || end<start ) {
fix indent please

2024-01-04 07:51 UTC, kossnikita commented
fix #23

2024-01-08 11:28 UTC, EGOKM commented
Hello again,
well it seems that haneefdm is not working on peripheral-viewer any more ? So I wanted to ask thegecko for some Review ?
Any Chance to check the PR ?
THX, Enrico

2024-01-17 12:26 UTC, EGOKM commented
just to avoid something like this:
![image](https://github.com/mcu-debug/peripheral-viewer/assets/111112114/ec4ba714-1d6d-42b1-9c9e-ec56cfa27f64)

2024-03-27 05:40 UTC, kossnikita commented on src/utils.ts
> +    	  return [];
still has indent issues
tabs instead spaces, 4 space indent
Please, use lint before commit

2024-03-27 05:40 UTC, kossnikita commented
Works fine to me
![image](https://github.com/mcu-debug/peripheral-viewer/assets/39294101/8f4f4735-daf8-4450-8c7e-d9b3387e0838)

2024-04-12 12:21 UTC, EGOKM commented
well, because kossnikita has verified it works - is it possible to merge and update ?

2024-04-19 09:21 UTC, EGOKM commented
@kossnikita well, because the pull request is still open :-( , its possible to send the working extension to me ?

2024-04-19 09:29 UTC, kossnikita commented
You have to build it by yourself. You require node.js and yarn

```bash
npx vsce package --yarn
```

It generates `peripheral-viewer-xxx.vsix` you can install with VS Code command `Extensions: Install from VSIX...`

2024-04-19 12:56 UTC, EGOKM commented
ok, THX, now it works also for me ;-)

2024-04-19 13:15 UTC, kossnikita commented
Please note, you should fix issues I mentioned before. Use `yarn lint` to check syntax

2025-07-19 07:41 UTC, merged